In [20]:
##### APPLY CLAHE TO DYSLEXIC DATA
import numpy as np
import cv2
import glob
from random import *
all_img = glob.glob("F:\\IIT KANPUR MTECH STUDY MATERIAL\\THESIS\\Data  of Dyslexic and Non Dyslexic Children in Hindi\\Both Data with Matra\\Dyslexia\\*")
#other_dir = "F:\\IIT KANPUR MTECH STUDY MATERIAL\\THESIS\\Data  of Dyslexic and Non Dyslexic Children in Hindi\\Both Data\\CLAHE"
for img_id, img_path in enumerate(all_img):
    img = cv2.imread(img_path,0) #three options for the second parameter; -1, 0, and 1, which correspond to Unchanged, Grayscale, and Color respectively.
    #print(img_id)

    #create a CLAHE object (Arguments are optional).
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(2,2))
    cl1 = clahe.apply(img)
    
     #create a OTSU object.
    ret, imgf = cv2.threshold(cl1, 0, 255, cv2.THRESH_BINARY+cv2.THRESH_OTSU)
    
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(2,2))
    opening = cv2.morphologyEx(imgf, cv2.MORPH_OPEN, kernel)
        
    other_dir = "F:\\IIT KANPUR MTECH STUDY MATERIAL\\THESIS\\Data  of Dyslexic and Non Dyslexic Children in Hindi\\Both Data with Matra\\after prepro\\Dyslexia" 
    cv2.imwrite(f'{other_dir}/open_dys_{img_id}.jpg',opening)   

In [2]:
#for non dyslexic data
import numpy as np
import cv2
import glob
from random import *
all_img = glob.glob("F:\\IIT KANPUR MTECH STUDY MATERIAL\\THESIS\\Data  of Dyslexic and Non Dyslexic Children in Hindi\\Both Data with Matra\\Non Dyslexia\\*")
#other_dir = "F:\\IIT KANPUR MTECH STUDY MATERIAL\\THESIS\\Data  of Dyslexic and Non Dyslexic Children in Hindi\\Both Data\\CLAHE"
for img_id, img_path in enumerate(all_img):
    img = cv2.imread(img_path,0) #three options for the second parameter; -1, 0, and 1, which correspond to Unchanged, Grayscale, and Color respectively.
    #print(img_id)

    #create a CLAHE object (Arguments are optional).
    clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(2,2))
    cl1 = clahe.apply(img)
    
     #create a OTSU object.
    ret, imgf = cv2.threshold(cl1, 0, 255, cv2.THRESH_BINARY+cv2.THRESH_OTSU)
    
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(3,3))
    opening = cv2.morphologyEx(imgf, cv2.MORPH_OPEN, kernel)
        
    other_dir = "F:\\IIT KANPUR MTECH STUDY MATERIAL\\THESIS\\Data  of Dyslexic and Non Dyslexic Children in Hindi\\Both Data with Matra\\Non Dyslexia After OTSU" 
    cv2.imwrite(f'{other_dir}/otsu_non_{img_id}.jpg',imgf)   

In [25]:
#for Geometrical Symmetrical Words
import numpy as np
import cv2
import glob
from random import *
all_img = glob.glob("F:\\IIT KANPUR MTECH STUDY MATERIAL\\THESIS\\Data  of Dyslexic and Non Dyslexic Children in Hindi\\GS\\vipreet\\*")
#other_dir = "F:\\IIT KANPUR MTECH STUDY MATERIAL\\THESIS\\Data  of Dyslexic and Non Dyslexic Children in Hindi\\Both Data\\CLAHE"
for img_id, img_path in enumerate(all_img):
#for img_id, img_path in all_img:
    img = cv2.imread(img_path,0) #three options for the second parameter; -1, 0, and 1, which correspond to Unchanged, Grayscale, and Color respectively.
    print(img_id)

    #create a CLAHE object (Arguments are optional).
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(2,2))
    cl1 = clahe.apply(img)
    
     #create a OTSU object.
    ret, imgf = cv2.threshold(cl1, 0, 255, cv2.THRESH_BINARY+cv2.THRESH_OTSU)
    print(imgf)
    
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(2,2))
    opening = cv2.morphologyEx(imgf, cv2.MORPH_OPEN, kernel)
        
    other_dir = "F:\\IIT KANPUR MTECH STUDY MATERIAL\\THESIS\\Data  of Dyslexic and Non Dyslexic Children in Hindi\\GS\\vipreet" 
    cv2.imwrite(f'{other_dir}/otsu_GS_dys_{img_id}.jpg',opening)   

0
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
1
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [1]:
# for 2 letters words
##### APPLY CLAHE TO DYSLEXIC DATA
import numpy as np
import cv2
import glob
from random import *
all_img = glob.glob("F:\\IIT KANPUR MTECH STUDY MATERIAL\\THESIS\\Data  of Dyslexic and Non Dyslexic Children in Hindi\\Dyslexic Data\\2 letter words\\All two letters words\\*")
#other_dir = "F:\\IIT KANPUR MTECH STUDY MATERIAL\\THESIS\\Data  of Dyslexic and Non Dyslexic Children in Hindi\\Both Data\\CLAHE"
for img_id, img_path in enumerate(all_img):
    img = cv2.imread(img_path,0) #three options for the second parameter; -1, 0, and 1, which correspond to Unchanged, Grayscale, and Color respectively.
    #print(img_id)

    #create a CLAHE object (Arguments are optional).
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(2,2))
    cl1 = clahe.apply(img)
    
     #create a OTSU object.
    ret, imgf = cv2.threshold(cl1, 0, 255, cv2.THRESH_BINARY+cv2.THRESH_OTSU)
    
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(2,2))
    opening = cv2.morphologyEx(imgf, cv2.MORPH_OPEN, kernel)
        
    other_dir = "F:\\IIT KANPUR MTECH STUDY MATERIAL\\THESIS\\Data  of Dyslexic and Non Dyslexic Children in Hindi\\Dyslexic Data\\2 letter words\\All two letters after pre" 
    cv2.imwrite(f'{other_dir}/open_dys_{img_id}.jpg',opening)   

In [3]:
# for 3 letters words
##### APPLY CLAHE TO DYSLEXIC DATA
import numpy as np
import cv2
import glob
from random import *
all_img = glob.glob("F:\\IIT KANPUR MTECH STUDY MATERIAL\\THESIS\\Data  of Dyslexic and Non Dyslexic Children in Hindi\\Dyslexic Data\\3 letter words\\All words\\*")
#other_dir = "F:\\IIT KANPUR MTECH STUDY MATERIAL\\THESIS\\Data  of Dyslexic and Non Dyslexic Children in Hindi\\Both Data\\CLAHE"
for img_id, img_path in enumerate(all_img):
    img = cv2.imread(img_path,0) #three options for the second parameter; -1, 0, and 1, which correspond to Unchanged, Grayscale, and Color respectively.
    #print(img_id)

    #create a CLAHE object (Arguments are optional).
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(2,2))
    cl1 = clahe.apply(img)
    
     #create a OTSU object.
    ret, imgf = cv2.threshold(cl1, 0, 255, cv2.THRESH_BINARY+cv2.THRESH_OTSU)
    
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(2,2))
    opening = cv2.morphologyEx(imgf, cv2.MORPH_OPEN, kernel)
        
    other_dir = "F:\\IIT KANPUR MTECH STUDY MATERIAL\\THESIS\\Data  of Dyslexic and Non Dyslexic Children in Hindi\\Dyslexic Data\\3 letter words\\All words after pre" 
    cv2.imwrite(f'{other_dir}/open_dys_{img_id}.jpg',opening)   

In [12]:
# for 4 letters words
##### APPLY CLAHE TO DYSLEXIC DATA
import numpy as np
import cv2
import glob
from random import *
#all_img = glob.glob("F:\\IIT KANPUR MTECH STUDY MATERIAL\\THESIS\\Data  of Dyslexic and Non Dyslexic Children in Hindi\\Dyslexic Data\\4 letter words\\All words\\*")
all_img = glob.glob("F:\\IIT KANPUR MTECH STUDY MATERIAL\\THESIS\\Data  of Dyslexic and Non Dyslexic Children in Hindi\\Dyslexic Data\\Compound words\\All words\\*")
#other_dir = "F:\\IIT KANPUR MTECH STUDY MATERIAL\\THESIS\\Data  of Dyslexic and Non Dyslexic Children in Hindi\\Both Data\\CLAHE"
for img_id, img_path in enumerate(all_img):
    img = cv2.imread(img_path,0) #three options for the second parameter; -1, 0, and 1, which correspond to Unchanged, Grayscale, and Color respectively.
    #print(img_id)

    #create a CLAHE object (Arguments are optional).
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(2,2))
    cl1 = clahe.apply(img)
    
     #create a OTSU object.
    ret, imgf = cv2.threshold(cl1, 0, 255, cv2.THRESH_BINARY+cv2.THRESH_OTSU)
    
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(2,2))
    opening = cv2.morphologyEx(imgf, cv2.MORPH_OPEN, kernel)
        
    other_dir = "F:\\IIT KANPUR MTECH STUDY MATERIAL\\THESIS\\Data  of Dyslexic and Non Dyslexic Children in Hindi\\Dyslexic Data\\Compound words\\All words after pre" 
    cv2.imwrite(f'{other_dir}/open_dys_{img_id}.jpg',opening)   

In [3]:
# for 2 letters words
##### APPLY CLAHE TO Non DYSLEXIC DATA
import numpy as np
import cv2
import glob
from random import *
#all_img = glob.glob("F:\\IIT KANPUR MTECH STUDY MATERIAL\\THESIS\\Data  of Dyslexic and Non Dyslexic Children in Hindi\\Non Dyslexic Data\\2 letters words\\All words\\*")
all_img = glob.glob("F:\\IIT KANPUR MTECH STUDY MATERIAL\\THESIS\\Data  of Dyslexic and Non Dyslexic Children in Hindi\\Non Dyslexic Data\\3 letters words\\All words\\*")
#all_img = glob.glob("F:\\IIT KANPUR MTECH STUDY MATERIAL\\THESIS\\Data  of Dyslexic and Non Dyslexic Children in Hindi\\Non Dyslexic Data\\4 letters words\\All words\\*")
#all_img = glob.glob("F:\\IIT KANPUR MTECH STUDY MATERIAL\\THESIS\\Data  of Dyslexic and Non Dyslexic Children in Hindi\\Non Dyslexic Data\\compound letter\\All words\\*")
#other_dir = "F:\\IIT KANPUR MTECH STUDY MATERIAL\\THESIS\\Data  of Dyslexic and Non Dyslexic Children in Hindi\\Both Data\\CLAHE"
for img_id, img_path in enumerate(all_img):
    img = cv2.imread(img_path,0) #three options for the second parameter; -1, 0, and 1, which correspond to Unchanged, Grayscale, and Color respectively.
    #print(img_id)

    #create a CLAHE object (Arguments are optional).
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(2,2))
    cl1 = clahe.apply(img)
    
     #create a OTSU object.
    ret, imgf = cv2.threshold(cl1, 0, 255, cv2.THRESH_BINARY+cv2.THRESH_OTSU)
    
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(2,2))
    opening = cv2.morphologyEx(imgf, cv2.MORPH_OPEN, kernel)
        
    other_dir = "F:\\IIT KANPUR MTECH STUDY MATERIAL\\THESIS\\Data  of Dyslexic and Non Dyslexic Children in Hindi\\Non Dyslexic Data\\3 letters words\\All words after pre" 
    cv2.imwrite(f'{other_dir}/open_dys_{img_id}.jpg',opening)   